import = ["/Users/yuhsienchiang/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"
TERMINAL = "alacritty"

[window]
decorations = "buttonless"
dynamic_title = false
opacity = 1.0
padding = {x = 12, y = 10}
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[scrolling]
history = 10000
multiplier = 2

[font]
size = 15.0
normal = { family ="MesloLGL Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[cursor]
style = { shape = "Beam",  blinking= "Always" }
unfocused_hollow = true

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key="Paste",                                         action="Paste"                 },
    { key="Copy",                                          action="Copy"                  },
    { key="Key0",           mods="Command",                action="ResetFontSize"         },
    { key="Plus",           mods="Command",                action="IncreaseFontSize"      },
    { key="Minus",          mods="Command",                action="DecreaseFontSize"      },
    { key="V",              mods="Command",                action="Paste"                 },
    { key="C",              mods="Command",                action="Copy"                  },
    { key="Q",              mods="Command",                action="Quit"                  },
    { key="N",              mods="Command",                action="SpawnNewInstance"      },
    { key="E",              mods="Command",                chars="\u0001\u0065"           },
    { key="D",              mods="Command",                chars="\u0001\u0076"           },
    { key="D",              mods="Command|Shift",          chars="\u0001\u0073"           },
    { key="W",              mods="Command",                chars="\u0001\u0078"           },
    { key="RBracket",       mods="Command",                chars="\u0001\u005D"           },
    { key="LBracket",       mods="Command",                chars="\u0001\u005B"           },
    { key="Backslash",      mods="Command",                chars="\u0001\u0071"           },
    { key="T",              mods="Command",                chars="\u0001\u0063"           },
    { key="K",              mods="Command",                chars="\u0001\u006B"           },
    { key="Key1",           mods="Command",                chars="\u0001\u0031"           },
    { key="Key2",           mods="Command",                chars="\u0001\u0032"           },
    { key="Key3",           mods="Command",                chars="\u0001\u0033"           },
    { key="Key4",           mods="Command",                chars="\u0001\u0034"           },
    { key="Key5",           mods="Command",                chars="\u0001\u0035"           },
    { key="Key6",           mods="Command",                chars="\u0001\u0036"           },
    { key="Key7",           mods="Command",                chars="\u0001\u0037"           },
    { key="Key8",           mods="Command",                chars="\u0001\u0038"           },
    { key="Key9",           mods="Command",                chars="\u0001\u0039"           },
    { key="Left",           mods="Command",                chars="\u0001\u0070"           },
    { key="Right",          mods="Command",                chars="\u0001\u006E"           },
]
