format = """\
$os\
$directory\
${custom.git_remote}\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """\
$status\
$jobs\
[$python$conda$nodejs$java$lua$c$haskell](teal dimmed)\
$docker_context\
$aws\
$azure\
"""

add_newline = true
palette = "catppuccin_mocha"

# Left
[os]
style = 'text text'
disabled = false

[os.symbols]
Android = " "
Arch    = " "
Debian  = " "
Linux   = " "
Macos   = " "
NixOS   = " "
Redhat  = " "
Ubuntu  = " "
Unknown = " "
Windows = "󰍲 "

[directory]
format                    = '[$read_only]($read_only_style)[$path]($style) '
read_only                 = "󰌾 "
truncate_to_repo          = false
fish_style_pwd_dir_length = 3
truncation_length         = 4
style                     = "blue bold"

[git_branch]
symbol = " "
format = '[$symbol$branch]($style) '
style  = "green bold"

[git_state]
format='[$state( \($progress_current/$progress_total\))]($style) '
style = "red bold"

[git_status]
format = """
[$conflicted](red bold)\
[$ahead_behind](green bold)\
[$stashed](green bold)\
[$deleted$renamed$typechanged](maroon bold)\
[$staged$modified](peach bold)\
[$untracked](blue bold)"""
conflicted        = '󰘕${count} '
ahead             = '⇡${count} '
behind            = '⇣${count} '
diverged          = '⇕⇡${ahead_count}⇣${behind_count}'
stashed	          = '${count} '
untracked	      = '?${count} '
modified          = '✘${count} '
staged	          = '✓${count} '
renamed	          = '󰄾${count} '
deleted           = '󰗨${count} '
typechanged       = '󰁪${count} '
ignore_submodules =	false
disabled          =	false

[character]
format                    ='$symbol '
success_symbol            ='[❯](bold sapphire)[❯](bold sky)[❯](bold green)'
error_symbol              ='[❯](bold yellow)[❯](bold peach)[❯](bold red)'
vimcmd_symbol             ='[](bold mauve)[❮](bold pink)[❮](bold flamingo)'

# Right
[status]
format                = '[$symbol $status]($style) '
symbol                = '✘'	
success_symbol        = ''
not_executable_symbol = ''
not_found_symbol      = ''
sigint_symbol         = '✘'
signal_symbol         = '󱐋'
style                 = 'red'
disabled              = false

[jobs]
symbol = " "

[python]
format         = '${symbol}($virtualenv) (${version})'
version_format = '${raw}'
symbol         = " "

[conda]
format = '$symbol($version )'
symbol = " "

[nodejs]
format         = '$symbol($version )'
version_format = '${raw}'
symbol         = " "

[java]
format         = '$symbol($version )'
version_format = '${raw}'
symbol         = " "

[lua]
format         = '$symbol($version )'
version_format = '${raw}'
symbol         = " "

[c]
format         = '$symbol($version(-$name) )'
version_format = '${raw}'
symbol         = " "

[haskell]
format = '$symbol($version )'
symbol = " "

[docker_context]
format = '$symbol$context '
symbol = "󰡨 "

[aws]
format = '$symbol($profile )(\($region\) )(\[$duration\] )'
symbol = "󰸏 "

[azure]
format = '$symbol($subscription) '
symbol = "󰠅"

[custom.git_remote]
description = "Display symbol for remote Git server"
command = "$HOME/.config/starship/get_git_remote.zsh"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash", "--noprofile", "--norc"]
format = "on [$output]($style) "

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo  = "#f0c6c6"
pink      = "#f5bde6"
mauve     = "#c6a0f6"
red       = "#ed8796"
maroon    = "#ee99a0"
peach     = "#f5a97f"
yellow    = "#eed49f"
green     = "#a6da95"
teal      = "#8bd5ca"
sky       = "#91d7e3"
sapphire  = "#7dc4e4"
blue      = "#8aadf4"
lavender  = "#b7bdf8"
text      = "#cad3f5"
subtext1  = "#b8c0e0"
subtext0  = "#a5adcb"
overlay2  = "#939ab7"
overlay1  = "#8087a2"
overlay0  = "#6e738d"
surface2  = "#5b6078"
surface1  = "#494d64"
surface0  = "#363a4f"
base      = "#24273a"
mantle    = "#1e2030"
crust     = "#181926"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo  = "#eebebe"
pink      = "#f4b8e4"
mauve     = "#ca9ee6"
red       = "#e78284"
maroon    = "#ea999c"
peach     = "#ef9f76"
yellow    = "#e5c890"
green     = "#a6d189"
teal      = "#81c8be"
sky       = "#99d1db"
sapphire  = "#85c1dc"
blue      = "#8caaee"
lavender  = "#babbf1"
text      = "#c6d0f5"
subtext1  = "#b5bfe2"
subtext0  = "#a5adce"
overlay2  = "#949cbb"
overlay1  = "#838ba7"
overlay0  = "#737994"
surface2  = "#626880"
surface1  = "#51576d"
surface0  = "#414559"
base      = "#303446"
mantle    = "#292c3c"
crust     = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo  = "#dd7878"
pink      = "#ea76cb"
mauve     = "#8839ef"
red       = "#d20f39"
maroon    = "#e64553"
peach     = "#fe640b"
yellow    = "#df8e1d"
green     = "#40a02b"
teal      = "#179299"
sky       = "#04a5e5"
sapphire  = "#209fb5"
blue      = "#1e66f5"
lavender  = "#7287fd"
text      = "#4c4f69"
subtext1  = "#5c5f77"
subtext0  = "#6c6f85"
overlay2  = "#7c7f93"
overlay1  = "#8c8fa1"
overlay0  = "#9ca0b0"
surface2  = "#acb0be"
surface1  = "#bcc0cc"
surface0  = "#ccd0da"
base      = "#eff1f5"
mantle    = "#e6e9ef"
crust     = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7" # purple like
red       = "#f38ba8"
maroon    = "#eba0ac" # red like
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"
