gui:
  branchColors: {}
  scrollHeight: 2
  scrollPastBottom: true
  nerdFontsVersion: "3"
  splitDiff: auto
  theme:
    activeBorderColor:
      - '#a6d189'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#a6d189'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'
  authorColors:
    '*': '#babbf1'
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never
        useConfig: false
    commit:
        signOff: false
    branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
    allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
