#!/bin/zsh

sesh cn "$(sesh list | \
    fzf-tmux \
        -q "$*" \
        -p 55%,60% \
        --no-sort \
        --border-label ' sesh ' \
        --prompt '󱐋  ' \
        --header '^a all | ^t tmux | ^x zoxide | ^d kill | ^f find' \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-a:change-prompt(󱐋  )+reload(sesh list)' \
        --bind 'ctrl-t:change-prompt(  )+reload(sesh list -t)' \
        --bind 'ctrl-x:change-prompt(  )+reload(sesh list -z)' \
        --bind 'ctrl-f:change-prompt(󰍉  )+reload(fd -H -d 5 -t d . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(󱐋  )+reload(sesh list)')"
